obstacle_range: 3.5
raytrace_range: 4.0
footprint: [[0.23, 0.18], [-0.23, 0.18], [-0.23, -0.18], [0.23, -0.18]]
#robot_radius: ir_of_robot
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: horizontal_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
