global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.0
  rolling_window: true
  origin_x: 0.0
  origin_y: 0.0
  width: 5.0
  height: 5.0
  static_map: true
  resolution: 0.05
