global_costmap:
  plugins: 
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: false
  resolution: 0.05
  inflation_radius: 0.45
  map_topic: map
