global_costmap:
  plugins: 
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: nav_link
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: false
  resolution: 0.05
  map_topic: map
  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 1.0
