local_costmap:
  # plugins: 
  # #   - {name: static_layer, type: "costmap_2d::StaticLayer"}
  #   - {name: obstacles,       type: "costmap_2d::VoxelLayer"}
  #   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.05
  inflation_radius: 0.35

  observation_sources: laser_scan_sensor

  laser_scan_sensor: {sensor_frame: horizontal_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
